
# This file contains a configuration set for anvil gen and build commands.
# The general structure of set is following:

[clang-ninja]
    generator = "Ninja"

    [[clang-ninja.gen]]
        target = "Debug"
        out_dir = "build/Debug"
        args = "-DCMAKE_BUILD_TYPE=Debug"

    [[clang-ninja.gen]]
        target = "Release"
        out_dir = "build/Release"
        args = "-DCMAKE_BUILD_TYPE=Release"

    [[clang-ninja.build]]
        mode = ""
        args = "-- -j 8"
