
# This file contains a configuration set for anvil gen and build commands.
# The general structure of set is following:

# Defines a configuration
[msvc-2019]
    generator = "Visual Studio 16 2019"
    # Defines generate-target collection
    [[msvc-2019.gen]]
        target = ""    # can be empty, but must be unique if multiple generate-target is possible.
        out_dir = "build/msvc-2019" # relative project root
        args = ""

    [[msvc-2019.build]]
        mode = "Debug"
        args = "--target ALL_BUILD --config Debug"

    [[msvc-2019.build]]
        mode = "Release"
        args = "--target ALL_BUILD --config Debug"

[clang-ninja]
    generator = "Ninja"

    [[clang-ninja.gen]]
        target = "Debug"
        out_dir = "build/Debug"
        args = "-DCMAKE_BUILD_TYPE=Debug"

    [[clang-ninja.gen]]
        target = "Release"
        out_dir = "build/Release"
        args = "-DCMAKE_BUILD_TYPE=Release"

    [[clang-ninja.build]]
        mode = ""
        args = "-- -j 8"
